version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - api-network
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped

  database:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - api-network
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  api-network:
    driver: bridge

volumes:
  db-data:
